// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListChanges() {
  return window['go']['main']['App']['ListChanges']();
}

export function LoadPatch(arg1) {
  return window['go']['main']['App']['LoadPatch'](arg1);
}
